name: Release JAR

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

jobs:

  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Generate FAT Jar
        run: ./gradlew shadowJar

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build/libs/TJ-JShell-Backend.jar
